# Generated by Django 3.0 on 2022-03-21 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BUbotApp', '0002_chatmsg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatMsg',
        ),
    ]
