# Generated by Django 3.0 on 2022-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUbotApp', '0003_delete_chatmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='parallel_corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.CharField(max_length=1024)),
                ('final_answer', models.CharField(max_length=1024)),
                ('dynamic', models.BooleanField()),
            ],
        ),
    ]
